title: Resume | Najam Ul Saqib
description:  My resume made with jekyll
url: https://njmulsqb.github.io/my-resume
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
